GET http://localhost:3000/api/v1/users

###

GET http://localhost:3000/api/v1/users/varun.allenghost@gmail.com

###

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Varun Gupta",
  "dob": "1997-07-29",
  "email": "varungupta2015135@gmail.com"
}

###

PUT http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "id": 1,
  "name": "Varun Gupta",
  "bio": ""
}